#!/usr/bin/env bash
INSTRUCTION=$1

if [ $INSTRUCTION ]
then
    MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
    CUR_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)

    if [[ $INSTRUCTION == "up" ]]
    then
        NEW_BRIGHTNESS=$(echo "$CUR_BRIGHTNESS + 25" | bc)
        if [[ $NEW_BRIGHTNESS -lt $MAX_BRIGHTNESS ]]
        then
            echo $NEW_BRIGHTNESS > /sys/class/backlight/intel_backlight/brightness
        else
            echo $MAX_BRIGHTNESS > /sys/class/backlight/intel_backlight/brightness
        fi
    elif [[ $INSTRUCTION == "down" ]]
    then
        NEW_BRIGHTNESS=$(echo "$CUR_BRIGHTNESS - 25" | bc)
        if [[ $NEW_BRIGHTNESS -gt 1 ]]
        then
            echo $NEW_BRIGHTNESS > /sys/class/backlight/intel_backlight/brightness
        else
            echo 1 > /sys/class/backlight/intel_backlight/brightness
        fi
    fi
else
    printf "%d%%" $(echo "(" $(cat /sys/class/backlight/intel_backlight/brightness) / $(cat /sys/class/backlight/intel_backlight/max_brightness) ") * 100" | bc -l | grep -Eo "^[0-9]+")
fi
