#!/usr/bin/env bash
printf "%d%%" $(echo "(" $(cat /sys/class/backlight/intel_backlight/brightness) / $(cat /sys/class/backlight/intel_backlight/max_brightness) ") * 100" | bc -l | grep -Eo "^[0-9]+")
